import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/ELEMENTX/abstract/abstract.css';
import '@/css/index.css';
import Nav from "@/components/home/nav/Nav";
import './globals.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
        </body>
    </html>
  );
}
